//! Generate the Codex and OpenCode agent mirrors from the canonical Claude agents.
//!
//! Both generators copy the prompt body byte-for-byte and PROVE the round trip
//! before they write a file:
//!
//! * Codex: `.codex/agents/<slug>.toml` with `name`, `description`, and the
//!   complete Markdown source in `developer_instructions`.
//! * OpenCode: `.opencode/agents/<slug>.md` with rewritten front matter
//!   (`description`, `mode`, `model`, `color`) and the unchanged body.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::{self, Write as _};
use std::path::{Path, PathBuf};

use anyhow::{Context as _, bail, ensure};

/// The model every generated OpenCode agent pins.
const OPENCODE_MODEL: &str = "openrouter/deepseek/deepseek-v4.1-flash";

/// Header line stamped on every generated Codex file.
const CODEX_NOTE: &str = "# Generated by `cargo xtask sync-agents`. Do not edit by hand.";

/// Header line stamped inside every generated OpenCode front matter.
const OPENCODE_NOTE: &str =
    "# Generated by `cargo xtask sync-agents` from .claude/agents. Do not edit by hand.";

/// Claude color names mapped to CSS hex values.
///
/// Claude Code accepts a named color; OpenCode accepts a hex color. Each entry
/// maps a Claude name to the CSS hex value of that name.
const COLORS: &[(&str, &str)] = &[
    ("amber", "#FFBF00"),
    ("blue", "#0000FF"),
    ("bronze", "#CD7F32"),
    ("cyan", "#00FFFF"),
    ("fuchsia", "#FF00FF"),
    ("gold", "#FFD700"),
    ("green", "#008000"),
    ("indigo", "#4B0082"),
    ("olive", "#808000"),
    ("orange", "#FFA500"),
    ("pink", "#FFC0CB"),
    ("purple", "#800080"),
    ("red", "#FF0000"),
    ("silver", "#C0C0C0"),
    ("teal", "#008080"),
    ("violet", "#EE82EE"),
    ("yellow", "#FFFF00"),
];

/// A root actor starts a session as the top-level agent (the operator selects
/// it, or a daemon runs `opencode run --agent <name>`) and another agent can
/// also spawn it. OpenCode mode `all` covers both uses. Every other agent is
/// only spawned, so it is a `subagent`.
const ROOT_ACTORS: &[&str] = &[
    "automated-orchestrator",
    "hypervisor",
    "hypervisor-turn",
    "orchestrator",
    "orchestrator-turn",
];

/// What a run found.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Outcome {
    /// Every mirror matches (or was rewritten to match).
    Clean,
    /// `--check` found a stale or unexpected mirror file.
    Drift,
}

/// One canonical Claude agent, parsed.
#[derive(Debug)]
struct Agent {
    /// File stem: the agent identifier in both mirrors.
    slug: String,
    /// The complete Markdown source.
    source: String,
    /// The body after the front matter block.
    body: String,
    /// Front matter fields, one `key: value` pair per line.
    fields: BTreeMap<String, String>,
    /// Where it came from, for messages.
    path: PathBuf,
}

/// Split `---\n<block>\n---\n` off the front of a file.
///
/// Returns `(block, body)`.
fn split_front_matter(source: &str) -> Option<(&str, &str)> {
    let rest = source.strip_prefix("---\n")?;
    let end = rest.find("\n---\n")?;
    let block = rest.get(..end)?;
    let body = rest.get(end.checked_add("\n---\n".len())?..)?;
    Some((block, body))
}

/// Parse one `key: value` pair per line; the value is kept raw so an unquoted
/// colon inside a description stays exactly as written.
fn parse_fields(block: &str, path: &Path) -> anyhow::Result<BTreeMap<String, String>> {
    let mut fields = BTreeMap::new();
    for line in block.lines() {
        let Some((key, value)) = line.split_once(':') else {
            bail!("unparsed front matter line in {}: {line}", path.display());
        };
        let valid = key
            .chars()
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
            && key
                .chars()
                .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-'));
        ensure!(
            valid,
            "unparsed front matter line in {}: {line}",
            path.display()
        );
        fields.insert(key.to_owned(), value.trim_start().to_owned());
    }
    Ok(fields)
}

/// Every `.md` file below `dir`, sorted, recursing into subdirectories.
fn walk_markdown(dir: &Path, out: &mut Vec<PathBuf>) -> anyhow::Result<()> {
    let mut entries = fs::read_dir(dir)
        .with_context(|| format!("read {}", dir.display()))?
        .collect::<Result<Vec<_>, io::Error>>()?;
    entries.sort_by_key(fs::DirEntry::file_name);
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            walk_markdown(&path, out)?;
        } else if path.extension().is_some_and(|ext| ext == "md") {
            out.push(path);
        }
    }
    Ok(())
}

/// Load every canonical agent.
fn load_agents(source_root: &Path) -> anyhow::Result<Vec<Agent>> {
    let mut paths = Vec::new();
    walk_markdown(source_root, &mut paths)?;
    let mut seen = BTreeSet::new();
    let mut agents = Vec::new();
    for path in paths {
        let source =
            fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
        let Some((block, body)) = split_front_matter(&source) else {
            bail!("missing YAML front matter: {}", path.display());
        };
        let slug = path
            .file_stem()
            .map(|s| s.to_string_lossy().into_owned())
            .with_context(|| format!("no file stem: {}", path.display()))?;
        ensure!(
            seen.insert(slug.clone()),
            "two Claude agents share the slug {slug}"
        );
        let fields = parse_fields(block, &path)?;
        agents.push(Agent {
            slug,
            body: body.to_owned(),
            fields,
            source,
            path,
        });
    }
    Ok(agents)
}

/// A required front matter field.
fn require<'a>(agent: &'a Agent, key: &str) -> anyhow::Result<&'a str> {
    match agent.fields.get(key).map(String::as_str) {
        Some(value) if !value.is_empty() => Ok(value),
        Some(_) | None => bail!("missing front matter {key}: {}", agent.path.display()),
    }
}

/// Render the Codex TOML for one agent and prove it round-trips.
fn render_codex(agent: &Agent) -> anyhow::Result<String> {
    let description = require(agent, "description")?;
    let instructions = if agent.source.contains("'''") {
        serde_json::to_string(&agent.source)?
    } else {
        format!("'''\n{}'''", agent.source)
    };
    let output = format!(
        "{CODEX_NOTE}\nname = {}\ndescription = {}\ndeveloper_instructions = {instructions}\n",
        serde_json::to_string(&agent.slug)?,
        serde_json::to_string(description)?,
    );
    let decoded: toml::Table = toml::from_str(&output)
        .with_context(|| format!("emitted TOML does not parse: {}", agent.path.display()))?;
    let round_trip = decoded
        .get("developer_instructions")
        .and_then(toml::Value::as_str);
    ensure!(
        round_trip == Some(agent.source.as_str()),
        "agent prompt did not round-trip through TOML: {}",
        agent.path.display()
    );
    Ok(output)
}

/// Render the OpenCode Markdown for one agent and prove it round-trips.
fn render_opencode(agent: &Agent) -> anyhow::Result<String> {
    let description = require(agent, "description")?;
    let color_name = require(agent, "color")?;
    let Some((_, color)) = COLORS.iter().find(|(name, _)| *name == color_name) else {
        bail!("unmapped color {color_name:?}: {}", agent.path.display());
    };
    let mode = if ROOT_ACTORS.contains(&agent.slug.as_str()) {
        "all"
    } else {
        "subagent"
    };
    let quoted_description = serde_json::to_string(description)?;
    let front_matter = format!(
        "---\n{OPENCODE_NOTE}\ndescription: {quoted_description}\nmode: {mode}\nmodel: {OPENCODE_MODEL}\ncolor: {}\n---\n",
        serde_json::to_string(color)?
    );
    let output = format!("{front_matter}{}", agent.body);
    let Some((emitted_block, emitted_body)) = split_front_matter(&output) else {
        bail!(
            "emitted front matter does not split: {}",
            agent.path.display()
        );
    };
    ensure!(
        emitted_body == agent.body,
        "agent body did not round-trip: {}",
        agent.path.display()
    );
    let emitted_description = emitted_block
        .lines()
        .find_map(|line| line.strip_prefix("description: "))
        .with_context(|| {
            format!(
                "description line missing after emit: {}",
                agent.path.display()
            )
        })?;
    let decoded: String = serde_json::from_str(emitted_description)?;
    ensure!(
        decoded == description,
        "description did not round-trip: {}",
        agent.path.display()
    );
    Ok(output)
}

/// One generated mirror: where it lives and what it must contain.
#[derive(Debug)]
struct Mirror<'a> {
    /// Human label for messages (`Codex`, `OpenCode`).
    label: &'a str,
    /// The mirror directory.
    output_root: PathBuf,
    /// The file extension every mirror file carries.
    extension: &'a str,
    /// Expected path -> content.
    expected: BTreeMap<PathBuf, String>,
}

/// Write or check one mirror directory.
///
/// Returns `true` when drift was found in check mode.
fn reconcile(
    root: &Path,
    mirror: &Mirror<'_>,
    check: bool,
    err: &mut impl io::Write,
) -> anyhow::Result<bool> {
    let Mirror {
        label,
        output_root,
        extension,
        expected,
    } = mirror;
    fs::create_dir_all(output_root)?;
    let mut drift = false;
    for (path, output) in expected {
        let current = fs::read_to_string(path).ok();
        if current.as_deref() == Some(output.as_str()) {
            continue;
        }
        if check {
            let shown = path.strip_prefix(root).unwrap_or(path);
            writeln!(
                err,
                "{label} agent port is out of date: {}",
                shown.display()
            )?;
            drift = true;
        } else {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, output).with_context(|| format!("write {}", path.display()))?;
        }
    }
    let expected_names: BTreeSet<_> = expected.keys().filter_map(|p| p.file_name()).collect();
    for entry in fs::read_dir(output_root)? {
        let entry = entry?;
        let path = entry.path();
        let is_mirror = path.extension().is_some_and(|ext| ext == *extension);
        if is_mirror && !expected_names.contains(&entry.file_name().as_os_str()) {
            let shown = path.strip_prefix(root).unwrap_or(&path);
            writeln!(err, "unexpected {label} agent port: {}", shown.display())?;
            drift = true;
        }
    }
    Ok(drift)
}

/// Generate (or check) both mirrors.
pub(crate) fn run(root: &Path, check: bool) -> anyhow::Result<Outcome> {
    let agents = load_agents(&root.join(".claude").join("agents"))?;
    ensure!(
        !agents.is_empty(),
        "no canonical agents found under .claude/agents"
    );

    let mut codex = Mirror {
        label: "Codex",
        output_root: root.join(".codex").join("agents"),
        extension: "toml",
        expected: BTreeMap::new(),
    };
    let mut opencode = Mirror {
        label: "OpenCode",
        output_root: root.join(".opencode").join("agents"),
        extension: "md",
        expected: BTreeMap::new(),
    };
    for agent in &agents {
        let codex_path = codex.output_root.join(format!("{}.toml", agent.slug));
        codex.expected.insert(codex_path, render_codex(agent)?);
        let opencode_path = opencode.output_root.join(format!("{}.md", agent.slug));
        opencode
            .expected
            .insert(opencode_path, render_opencode(agent)?);
    }

    let stderr = io::stderr();
    let mut err = stderr.lock();
    let codex_drift = reconcile(root, &codex, check, &mut err)?;
    let opencode_drift = reconcile(root, &opencode, check, &mut err)?;
    if codex_drift || opencode_drift {
        return Ok(Outcome::Drift);
    }

    let stdout = io::stdout();
    let mut out = stdout.lock();
    if check {
        writeln!(
            out,
            "Codex and OpenCode agent ports match the canonical Claude agents byte-for-byte."
        )?;
    } else {
        writeln!(
            out,
            "Codex and OpenCode agent ports updated ({} agents).",
            agents.len()
        )?;
    }
    Ok(Outcome::Clean)
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::{Agent, render_codex, render_opencode, split_front_matter};

    fn agent(source: &str) -> Agent {
        let (block, body) = split_front_matter(source).expect("front matter");
        let fields = super::parse_fields(block, &PathBuf::from("t.md")).expect("fields");
        Agent {
            slug: "hypervisor".to_owned(),
            source: source.to_owned(),
            body: body.to_owned(),
            fields,
            path: PathBuf::from("t.md"),
        }
    }

    #[test]
    fn codex_round_trips_a_literal_body() {
        let source =
            "---\nname: X\ndescription: Does: things\ncolor: silver\n---\n# Body\n\nit's fine\n";
        let toml = render_codex(&agent(source)).expect("render");
        assert!(
            toml.contains("developer_instructions = '''\n---\nname: X"),
            "literal string used"
        );
        let table: toml::Table = toml::from_str(&toml).expect("parse");
        assert_eq!(
            table["description"].as_str(),
            Some("Does: things"),
            "raw description"
        );
    }

    #[test]
    fn codex_falls_back_to_json_when_body_has_triple_quotes() {
        let source = "---\ndescription: d\ncolor: red\n---\nuse ''' here\n";
        let toml = render_codex(&agent(source)).expect("render");
        assert!(
            toml.contains("developer_instructions = \"---"),
            "basic string used"
        );
    }

    #[test]
    fn opencode_rewrites_only_front_matter() {
        let source =
            "---\nname: X\ndescription: Root: actor\ncolor: silver\nemoji: \"x\"\n---\nBODY\n";
        let md = render_opencode(&agent(source)).expect("render");
        assert!(md.starts_with("---\n# Generated"), "note first");
        assert!(md.contains("mode: all\n"), "hypervisor is a root actor");
        assert!(md.contains("color: \"#C0C0C0\"\n"), "silver maps to hex");
        assert!(md.ends_with("---\nBODY\n"), "body unchanged");
    }
}
